### ISSUE TITLE
Facing issue with pretty table and python 2.7. 

### ISSUE THREAD

**Issue by sachintaware** [uskudnik/amazon-glacier-cmd-interface#202]
This seems to be an old repo and not sure if amazon glacier cmd is supported. The documentation seems to have only aws cli method to communicate with glacier. This by default takes python 2.7 and gives error with pretty table. Tried installing pretty table and still does not work. Can we force using python 3.8 ? As that is the version seems to work with pretty table or can the below error be resolved?

```
Traceback (most recent call last):
  File "/usr/local/bin/glacier-cmd", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'prettytable' distribution was not found and is required by glacier
```

**Comment by ggarnier** [comment]
It doesn't seem to work with python 3 because it uses python 2 print statements. I'm not sure if that's the only incompatibility.

I'm also having issues with python 2.7. Not the same error, but also related with `prettytable`:

```
# glacier-cmd --help
Traceback (most recent call last):
  File "/usr/local/bin/glacier-cmd", line 11, in <module>
    load_entry_point('glacier==0.2.dev0', 'console_scripts', 'glacier-cmd')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/site-packages/glacier-0.2.dev0-py2.7.egg/glacier/glacier.py", line 19, in <module>
    from prettytable import PrettyTable
  File "build/bdist.linux-x86_64/egg/prettytable/__init__.py", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/prettytable-3.0.0-py2.7.egg/prettytable/prettytable.py", line 313
    raise Exception(f"Index {index} is invalid, must be an integer or slice")
                                                                           ^
SyntaxError: invalid syntax
```
