### ISSUE TITLE
Upload fails with 408 error

### ISSUE THREAD

**Issue by echamberlain** [uskudnik/amazon-glacier-cmd-interface#95]
My smaller uploads are successful, but this one keeps failing with the following error, any ideas?

Traceback (most recent call last): 295.36 KB/s, average 385.03 KB/s, eta 19:06:42.  
  File "/usr/local/bin/glacier-cmd", line 8, in <module>
    load_entry_point('glacier==0.2dev', 'console_scripts', 'glacier-cmd')()
  File "/Library/Python/2.7/site-packages/glacier-0.2dev-py2.7.egg/glacier/glacier.py", line 751, in main
    args.func(args)
  File "/Library/Python/2.7/site-packages/glacier-0.2dev-py2.7.egg/glacier/glacier.py", line 147, in wrapper
    return fn(_args, *_kwargs)
  File "/Library/Python/2.7/site-packages/glacier-0.2dev-py2.7.egg/glacier/glacier.py", line 300, in upload
    args.name, args.partsize, args.uploadid, args.resume)
  File "/Library/Python/2.7/site-packages/glacier-0.2dev-py2.7.egg/glacier/GlacierWrapper.py", line 62, in wrapper
    ret = fn(_args, *_kwargs)
  File "/Library/Python/2.7/site-packages/glacier-0.2dev-py2.7.egg/glacier/GlacierWrapper.py", line 204, in glacier_connect_wrap
    return func(_args, *_kwargs)
  File "/Library/Python/2.7/site-packages/glacier-0.2dev-py2.7.egg/glacier/GlacierWrapper.py", line 62, in wrapper
    ret = fn(_args, *_kwargs)
  File "/Library/Python/2.7/site-packages/glacier-0.2dev-py2.7.egg/glacier/GlacierWrapper.py", line 257, in sdb_connect_wrap
    return func(_args, *_kwargs)
  File "/Library/Python/2.7/site-packages/glacier-0.2dev-py2.7.egg/glacier/GlacierWrapper.py", line 62, in wrapper
    ret = fn(_args, *_kwargs)
  File "/Library/Python/2.7/site-packages/glacier-0.2dev-py2.7.egg/glacier/GlacierWrapper.py", line 1086, in upload
    writer.write(part)
  File "/Library/Python/2.7/site-packages/glacier-0.2dev-py2.7.egg/glacier/glaciercorecalls.py", line 129, in write
    data)
  File "/Library/Python/2.7/site-packages/boto/glacier/layer1.py", line 625, in upload_part
    response_headers=response_headers)
  File "/Library/Python/2.7/site-packages/boto/glacier/layer1.py", line 83, in make_request
    raise UnexpectedHTTPResponseError(ok_responses, response)
boto.glacier.exceptions.UnexpectedHTTPResponseError: Expected 204, got (408, code=RequestTimeoutException, message=Request timed out.)

**Comment by mraheel83** [comment]
Yesterday I setup glacier-cmd from current source code and I'm still getting this error when I'm uploading 140GB file.

I'm getting this error after 10GB upload out of 140GB. Please advise me how can I fix it.

Thanks

**Comment by gburca** [comment]
Does the gburca@85ef4aa tip/branch fix this issue for anyone? See also https://github.com/uskudnik/amazon-glacier-cmd-interface/issues/171#issuecomment-101495322.

**Comment by SitronNO** [comment]
In the last days I have tried to upload 248 different files, all ranging from 13Mb to 37Gb (total of 450GB). After three days of 408 errors every 1-6 hours, I tried the code from @gburca (85ef4aa6dd58a36a77e4406366ddc27c7813cf5e) It has now uploaded 250GB the last 24 hours without a single error. Will try some more, but this is promising!
